#!/usr/bin/python3.6

import tkinter as tk
from tkinter import ttk
from tkinter import *
from PIL import Image, ImageTk
import random
import time
import serial
import serial.tools.list_ports as port_list

count = 0
tot = 0
mean_y_pos = 0
start_time = 0
min_partial_init = 100000
min_partial = min_partial_init
min_mean_init = 100000
min_mean = min_mean_init
serialFlag = 0
flag_off = 1
flag_on = 1
max_rand_time = 2
min_rand_time = 1
Serial_def = 0


def tryagain_func(): 					#-------------------------------------------------------------
	root_1.destroy()
	SerialPort.write(b'R') # the value 'R' is sent to initially turn off the LED to syncronize it with the GUI setup
	global count, tot, mean_y_pos, min_partial, min_mean, flag_off, flag_on	
	count = 0
	tot = 0
	mean_y_pos = 0
	min_partial = 100000
	min_mean = 100000
	flag_off = 0
	flag_on = 1	
	first_screen()



def stop_func(): 					#-------------------------------------------------------------
	root.destroy()	
	global root_1
	root_1 = tk.Tk()
	root_1.title("The reaction game")
	global min_partial, min_mean, min_partial_init, min_mean_init	

	width_screen, height_screen = root_1.winfo_screenwidth(), root_1.winfo_screenheight() #read the dimensions of the screen
	width_root, height_root = int(width_screen/2),int(height_screen/2) #calculate the dimensions of the main window
	root_1.geometry("%dx%d" % (width_root, height_root)) #setup of the window dimensions
	root_1.resizable(width=False, height=False) #block the possibility to resize the dimensions of the window

	# backgroud setup
	image = Image.open("finalscreen.png")
	if image.size != (width_root, height_root):
	    image = image.resize((width_root, height_root), Image.ANTIALIAS)

	image = ImageTk.PhotoImage(image)
	bg_label = tk.Label(root_1, image = image)
	bg_label.place(x=0, y=0, relwidth=1, relheight=1)
	bg_label.image = image

	# text widget setup
	min_partial_text = Text(root_1)

	if min_partial != min_partial_init:
		min_partial_text.place(relx=.32, rely=.3)
		min_partial_text.insert(END, " The best partial time: "+str(min_partial))
		min_partial_text.config(state="disabled", font="times 15 italic", fg="#efe26e", width=25, height=1, 
			relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
	else:
		min_partial_text.place(relx=.33, rely=.3)
		min_partial_text.insert(END, "  The best partial time: None")
		min_partial_text.config(state="disabled", font="times 15 italic", fg="#efe26e", width=24, height=1, 
			relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")

	min_mean_text = Text(root_1)

	if min_mean != min_mean_init:
		min_mean_text.place(relx=.32, rely=.4)
		min_mean_text.insert(END, 3*" "+"The best mean time: "+str("{0:.4f}".format(min_mean)))
		min_mean_text.config(state="disabled", font="times 15 italic", fg="#efe26e", width=25, height=1, 
			relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
	else:
		min_mean_text.place(relx=.33, rely=.4)
		min_mean_text.insert(END, 3*" "+"The best mean time: None")
		min_mean_text.config(state="disabled", font="times 15 italic", fg="#efe26e", width=24, height=1, 
			relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
	
	#Buttons
	### Try again button
	tryagain_DimX = 100
	tryagain_DimY = 100
	image_tryagain = Image.open("tryagain.png")
	image_tryagain = image_tryagain.resize((tryagain_DimX,tryagain_DimY), Image.ANTIALIAS)
	photo_tryagain = ImageTk.PhotoImage(image_tryagain)
	tryagain_button = Button(root_1, image=photo_tryagain, command=tryagain_func)
	tryagain_button.config(width=tryagain_DimX, height=tryagain_DimY, bg="#1bddba", bd=0, relief="raised", 
				highlightbackground="#1bddba", activebackground="#f78ea2")
	tryagain_button.place(relx=.815, rely=.45, x=tryagain_DimX/2, y=-(tryagain_DimY)/2, anchor=NE)

	### Exit button
	exit_DimX = 80
	exit_DimY = 40
	image_exit = Image.open("exit.png")
	image_exit = image_exit.resize((exit_DimX,exit_DimY), Image.ANTIALIAS)
	photo_exit = ImageTk.PhotoImage(image_exit)
	exit_button = Button(root_1, image=photo_exit, command=root_1.destroy) 
	exit_button.config(width=exit_DimX, height=exit_DimY, bg="#64f4d2", bd=0, relief="raised", 
				highlightbackground="#64f4d2", activebackground="#f78ea2")
	exit_button.place(relx=.515, rely=.65, x=exit_DimX/2, y=-(exit_DimY)/2, anchor=NE)

	root_1.mainloop()



def Off():					#-------------------------------------------------------------
	global flag_off, flag_on, SerialPort, Serial_def
	if flag_off == 1 and Serial_def == 1:
		flag_off = 0	
		flag_on = 1
		rand_time=random.randint(min_rand_time, max_rand_time)
		time.sleep(rand_time)
		time_button.config(image=photo_red) # the button change color
		SerialPort.write(b'L0')
		time_func()



def On():					#-------------------------------------------------------------
	global flag_off, flag_on, SerialPort, Serial_def
	if flag_on == 1 and Serial_def == 1:
		flag_off = 1
		flag_on = 0
		rand_time=random.randint(min_rand_time, max_rand_time)
		time.sleep(rand_time)
		time_button.config(image=photo_green) # the button change color
		SerialPort.write(b'L1')
		time_func()



def time_func(): 					#-------------------------------------------------------------
	global count, tot, mean, mean_y_pos, end_time, min_partial, min_mean, delay_time	

	delay_time=int(SerialPort.read(6)[1:6], 16)/1000 # the delay time is red from the

	# lists of times
	number_lenght=11
	count=count+1
	
	if min_partial>delay_time: # calculate the minimum reactive time of the user
		min_partial=delay_time

	if count==8: # it deletes all the present times
		for i in range(1,8):
			text_user_l = Text(root)
			text_user_l.place(relx=.05, rely=i/11+0.07)
			text_user_l.insert(END, 2*" "+"N"+str(i)+":")	
			text_user_l.config(state="disabled", font="times 15 italic", fg="#efe26e", width=number_lenght, height=1, 
					relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
		count=1

	time_n = Text(root)
	time_n.place(relx=.05, rely=count/11+0.07)
	time_n.insert(END, 2*" "+"N"+str(count)+": "+str("{0:.4f}".format(delay_time)))	
	time_n.config(state="disabled", font="times 15 italic", fg="#efe26e", width=number_lenght, height=1, 
			relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
	tot=tot+delay_time
	
	#means		
	if count==7:
		mean_y_pos+=1
		mean=0
		mean=tot/count

		if min_mean>mean: # calculate the minimum mean of the reactive time of the user
			min_mean=mean

		mean_n = Text(root)
		mean_n.place(relx=.785, rely=mean_y_pos/11+0.07)
		mean_n.insert(END, 2*" "+"M"+str(mean_y_pos)+": "+str(mean))	
		mean_n.config(state="disabled", font="times 15 italic", fg="#efe26e", width=number_lenght, height=1, 
				relief=FLAT, bd=0, bg="#007972", highlightbackground="#64f4d2", highlightcolor="#007c74")
		tot=0
		if mean_y_pos==7:
			stop_func()



def main(event=None):					#-------------------------------------------------------------
	global time_button
	global photo_green, photo_red
	global root, SerialPort, port_choose, tkvar
	
	user = user_entry.get()
	root_0.destroy()
	root = tk.Tk()
	root.title("The reaction game")

	width_screen, height_screen = root.winfo_screenwidth(), root.winfo_screenheight() #read the dimensions of the screen
	width_root, height_root = int(width_screen/2),int(height_screen/2) #calculate the dimensions of the main window
	root.geometry("%dx%d" % (width_root, height_root)) #setup of the window dimensions
	root.resizable(width=False, height=False) #block the possibility to resize the dimensions of the window

	# backgroud setup
	image = Image.open("rootscreen.png")
	if image.size != (width_root, height_root):
	    image = image.resize((width_root, height_root), Image.ANTIALIAS)

	image = ImageTk.PhotoImage(image)
	bg_label = tk.Label(root, image = image)
	bg_label.place(x=0, y=0, relwidth=1, relheight=1)
	bg_label.image = image
	
	# text widget with the username	
	text_user = Text(root)
	text_user.place(relx=.5, rely=.12, anchor=CENTER)
	text_user.insert(END, "Welcome, "+user+"!")
	text_user.config(state="disabled", font="times 15 italic", fg="white", width=len(user)+len("Welcome,!")-len(user)//7, 
			height=1, relief=FLAT, bd=0, bg="#007972", highlightbackground="#007c74", highlightcolor="#007c74")

	# BUTTONS
	### Time button
	time_DimX=140
	time_DimY=140
	image_red = Image.open("time_red_bg.png")
	image_red = image_red.resize((time_DimX,time_DimY), Image.ANTIALIAS)
	photo_red = ImageTk.PhotoImage(image_red)
	image_green = Image.open("time_green_bg.png")
	image_green = image_green.resize((time_DimX,time_DimY), Image.ANTIALIAS)
	photo_green = ImageTk.PhotoImage(image_green)
	time_button = Button(root, image=photo_red)
	time_button.config(width=time_DimX/width_screen, height=time_DimY/height_screen, bg="#48cbb2", bd=0, relief="raised", 
				highlightbackground="#48cbb2", activebackground="#f78ea2")
	time_button.place(relx=.5, rely=.4, x=time_DimX/2, y=-(time_DimY)/2, anchor=NE)

	### Off button
	off_DimX=80
	off_DimY=40
	image_off = Image.open("Off.png")
	image_off = image_off.resize((off_DimX,off_DimY), Image.ANTIALIAS)
	photo_off = ImageTk.PhotoImage(image_off)
	off_button = Button(root, image=photo_off, command=Off)
	off_button.config(width=off_DimX/width_screen, height=off_DimY/height_screen, bg="#64f4d2", bd=0, relief="raised", 
				highlightbackground="#64f4d2", activebackground="#f78ea2")
	off_button.place(relx=.35, rely=.67, anchor=CENTER)

	### On button
	on_DimX=80
	on_DimY=40
	image_on = Image.open("On.png")
	image_on = image_on.resize((on_DimX,on_DimY), Image.ANTIALIAS)
	photo_on = ImageTk.PhotoImage(image_on)
	on_button = Button(root, image=photo_on, command=On)
	on_button.config(width=on_DimX/width_screen, height=on_DimY/height_screen, bg="#64f4d2", bd=0, relief="raised", 
				highlightbackground="#64f4d2", activebackground="#f78ea2")
	on_button.place(relx=.5, rely=.67, anchor=CENTER)

	### Stop button
	stop_DimX=80
	stop_DimY=40
	image_stop = Image.open("stop.png")
	image_stop = image_stop.resize((stop_DimX,stop_DimY), Image.ANTIALIAS)
	photo_stop = ImageTk.PhotoImage(image_stop)
	stop_button = Button(root, image=photo_stop, command=stop_func) 
	stop_button.config(width=stop_DimX/width_screen, height=stop_DimY/height_screen, bg="#64f4d2", bd=0, relief="raised", 
				highlightbackground="#64f4d2", activebackground="#f78ea2")
	stop_button.place(relx=.65, rely=.67, anchor=CENTER)	

	# Ports menù
	portsList = []

	ports = list(port_list.comports())
	for p in ports: 
		portsList.append((p)[0])

	tkvar = StringVar(root)
	tkvar.set('Set port') # set the default option
	 	
	popupMenu = OptionMenu(root, tkvar, *portsList)
	popupMenu.place(relx=.5, rely=.83, anchor=CENTER)
	popupMenu.config(bd=0, bg="#f74c6e", activebackground="#f10e3c", highlightbackground="#ce0c39", 
			font="times 15", relief=GROOVE, width=12)
	popupMenu['menu'].config(bg="#f74c6e", activebackground="#f10e3c", 
			font="times 15")

	### link function to change dropdown
	tkvar.trace('w', change_dropdown)

	root.mainloop()



def change_dropdown(*args):				#-------------------------------------------------------------
	global port_choose, SerialPort, Serial_def
	port_choose = tkvar.get()
	SerialPort = serial.Serial(port_choose, 115200, bytesize=8, parity="N", stopbits=1, 
					timeout=None, xonxoff=0, rtscts=0, dsrdtr=0)
	SerialPort.write(b'R') # the value 'R' is sent to initially turn off the LED to syncronize it with the GUI setup
	Serial_def = 1


def first_screen():					#-------------------------------------------------------------
	global user_entry
	global root_0

	root_0 = tk.Tk()
	root_0.title("The reaction game")

	width_screen, height_screen = root_0.winfo_screenwidth(), root_0.winfo_screenheight() #read the dimensions of the screen
	width_root, height_root = int(width_screen/2),int(height_screen/2) #calculate the dimensions of the main window
	root_0.geometry("%dx%d" % (width_root, height_root)) #setup of the window dimensions
	root_0.resizable(width=False, height=False) #block the possibility to resize the dimensions of the window

	# backgroud setup
	image = Image.open("firstscreen.png")
	if image.size != (width_root, height_root):
	    image = image.resize((width_root, height_root), Image.ANTIALIAS)

	image = ImageTk.PhotoImage(image)
	bg_label = tk.Label(root_0, image = image)
	bg_label.place(x=0, y=0, relwidth=1, relheight=1)
	bg_label.image = image
	
	# entry
	user_entry = Entry(root_0)
	user_entry.config(justify="center", font="times 18 italic")
	user_entry.place(relx=.53, rely=.425, x=100, anchor=NE)
	user_entry.bind("<Return>", main)

	# begin_button
	begin_DimX=90
	begin_DimY=45
	image_begin = Image.open("begin.png")
	image_begin = image_begin.resize((begin_DimX, begin_DimY), Image.ANTIALIAS)
	photo_begin = ImageTk.PhotoImage(image_begin)
	begin_button = Button(root_0, image=photo_begin, command=main)
	begin_button.config(width=begin_DimX, height=begin_DimY, bg="#64f4d2", bd=0, relief="raised", 
				highlightbackground="#64f4d2", activebackground="#f78ea2")
	begin_button.place(relx=.51, rely=.65, x=begin_DimX/2, y=-(begin_DimY)/2, anchor=NE)

	root_0.mainloop()

first_screen()

