#!/usr/bin/python3.6

import tkinter as tk
from tkinter import ttk
#from sqlalchemy.sql.expression import column

def callbackFunc(event):
     print("New Element Selected")
     
app = tk.Tk() 
app.geometry('200x100')

labelTop = tk.Label(app, text = "Choose your favourite month")
labelTop.grid(column=0, row=0)

comboExample = ttk.Combobox(app, values=["January", "February", "March", "April"])

comboExample.place(relx=.05, rely=.5)
comboExample.current(0)
comboExample.config(bg="#000")

comboExample.bind("<<ComboboxSelected>>", callbackFunc)

app.mainloop()
