#!/usr/bin/python3.6

from tkinter import *
import tkinter as ttk
import serial.tools.list_ports as port_list

ports_list = ['0']

root = Tk()

ports = list(port_list.comports())
for p in ports: 
	ports_list.append((p)[0])

ports_list.remove('0')

tkvar = StringVar(root)
tkvar.set('Set port') # set the default option
 
popupMenu = OptionMenu(root, tkvar, *ports_list)
popupMenu.place(relx=.5, rely=.5, anchor=CENTER)

def printFunc(*args):
	print(tkvar.get())

tkvar.trace('w', printFunc)

root.mainloop()
